In [2]:
#Task 1:
#1.Write a function to compute 5/0 and use try/except to catch the exceptions.
try:
    a=5/0
except:
    print("Error:division by zero")
finally:
    print("Executed successfully")
              

Error:division by zero
Executed successfully


In [5]:
'''
2.Implement a Python program to generate all sentences where 
subject is in ["Americans","Indians"] and 
verb is in ["Play", "watch"] and 
the object is in ["Baseball","cricket"].
Hint: Subject,Verb and Object should be declared in the program as shown below.
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

Output should come as below:
Americans play Baseball.
Americans play Cricket.
Americans watch Baseball.
Americans watch Cricket.
Indians play Baseball.
Indians play Cricket.
Indians watch Baseball.
Indians watch Cricket.
'''
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

for i in subjects:
    for j in verbs:
        for k in objects:
            print(i+' '+j+' '+k)
        




Americans  play Baseball
Americans  play Cricket
Americans  watch Baseball
Americans  watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


In [16]:
'''
Task 2:
1.Write a function so that the columns of the output matrix are powers of the input vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.
HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

'''
import numpy as np
def gen_matrix(ip_vector,N,increasing=False):
    if not increasing:
        mat=np.array([x**(N-i-1) for x in ip_vector for i in range(N)])
        op_mat=mat.reshape(ip_vector.size,N)
    elif increasing:
        mat=np.array([x**i for x in ip_vector for i in range(N)])
        op_mat=mat.reshape(ip_vector.size,N)
    return op_mat

ip_vector=np.array([1,2,3])
N=3

print("matrix in decreasing order of powers:\n\n",gen_matrix(ip_vector,N,False),"\n\n")
print("matrix in decreasing order of powers:\n\n",gen_matrix(ip_vector,N,True),"\n\n")        
    

matrix in decreasing order of powers:

 [[1 1 1]
 [4 2 1]
 [9 3 1]] 


matrix in decreasing order of powers:

 [[1 1 1]
 [1 2 4]
 [1 3 9]] 


